columns:
  - name: 作业
    type: Literal("入职", "离职", "变更") 
  - name: 证件号码
    type: str # 同义词，例如："身份证号"、"身份证号码"等
  - name: 姓名
    type: str # 同义词，例如："Employee Name (Chinese)"、"姓名（中文）"、"员工姓名"等
  - name: 客户名称
    type: str # 有些被标注为"公司"
  - name: 户籍
    type: str # 同义词，例如："户籍所在地"、"户籍地区"等
  - name: 用工模式
    type: Literal("派遣", "商保", "代发")
  - name: 入职日期
    type: str # 同义词，例如："雇佣日"、"入职日"、"Hire Date"、"上岗日期"等
  - name: 合同终止日期
    type: str # 同义词，例如："Contract End"、"劳动合同止"等
  - name: 离职日期
    type: str #  同义词，例如："最后工作日期"等
  - name: 社保缴纳城市
    type: str # 同义词，例如："社保缴纳地"、"社保缴纳地区"等
  - name: 社保基数
    type: str #同义词，例如："基础工资"、"基础薪资"、"Base Pay"、"工资"等
  - name: 公积金基数
    type: str # 同义词，例如："公积金基数"等
  - name: 社保最后缴纳月
    type: str # 年月
  - name: 公积金最后缴纳月
    type: str # 年月
  - name: 成本中心
    type: str # 同义词，例如："Cost Center Name"、"部门"等
  - name: 内部工号
    type: str # 同义词，例如："Employee ID"、"员工编号"、"编号"、"工号"等
  - name: 备注
    type: str
  - name: 行颜色
    type: str
